import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { Josefin_Sans } from "next/font/google";

const josefin = Josefin_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-josefin-sans"
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${josefin.variable} bg-background text-foreground min-h-screen font-sans`}
      >
        <nav className="w-full flex items-center justify-between px-6 py-4 shadow-sm bg-white backdrop-blur-md border-b border-gray-100 sticky top-0 z-20">
          <div className="flex items-center gap-2">
            <span className="font-bold text-xl tracking-tight rounded-lg px-2 py-1 text-gray-900">
              SmartInch
            </span>
          </div>
          <div className="flex gap-4">
            <Link
              href="/dashboard"
              className="text-gray-700 hover:text-black font-medium transition"
            >
              Dashboard
            </Link>
            <Link
              href="/create"
              className="text-gray-700 hover:text-black font-medium transition"
            >
              Create Subscription
            </Link>
          </div>
        </nav>
        <main className="max-w-6xl mx-auto px-4 py-8 w-full">{children}</main>
      </body>
    </html>
  );
}
